package rest.onlyfriends.repository

import rest.onlyfriends.models.Response
import rest.onlyfriends.models.Star

class StarRepositoryLimitedImp : StarRepositoryLimit {
    override val stars = listOf(
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 2,
            name = "Cumbia Libertad",
            image = "/images/2.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 3,
            name = "Cumbia Libertad",
            image = "/images/3.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 4,
            name = "Cumbia Libertad",
            image = "/images/4.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 5,
            name = "Cumbia Libertad",
            image = "/images/5.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 6,
            name = "Cumbia Libertad",
            image = "/images/6.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 7,
            name = "Cumbia Libertad",
            image = "/images/7.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 8,
            name = "Cumbia Libertad",
            image = "/images/8.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 9,
            name = "Cumbia Libertad",
            image = "/images/9.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 10,
            name = "Cumbia Libertad",
            image = "/images/10.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 11,
            name = "Cumbia Libertad",
            image = "/images/11.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 12,
            name = "Cumbia Libertad",
            image = "/images/12.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 13,
            name = "Cumbia Libertad",
            image = "/images/13.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 14,
            name = "Cumbia Libertad",
            image = "/images/14.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 15,
            name = "Cumbia Libertad",
            image = "/images/15.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),
        Star(
            id = 16,
            name = "Cumbia Libertad",
            image = "/images/16.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
        ),

        )


    override suspend fun getAllStars(page: Int, limit: Int): Response {
        TODO("Not yet implemented")
    }

    override suspend fun searchStars(name: String): Response {
        return Response(
            succes = true,
            message = "Oke",
            allStars = findStars(query = name),
        )
    }

    private fun calculatePage(
        stars: List<Star>,
        page: Int,
        limit: StarRepositoryLimit,
    )

    private fun findStars(query: String?): List<Star> {
        val found = mutableListOf<Star>()
        return if (!query.isNullOrEmpty()) {
            stars.forEach { star ->
                if (star.name.lowercase().contains(query.lowercase())) {
                    found.add(star)
                }

            }
            found

        } else {
            emptyList()
        }
    }
}