package rest.onlyfriends.repository

import rest.onlyfriends.models.Response
import rest.onlyfriends.models.Star

class StarRepositoryLimitedImp : StarRepositoryLimit {
    override val stars = listOf(
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),
        Star(
            id = 1,
            name = "Cumbia Libertad",
            image = "/images/1.jpg",
            about = "here to share my (mostly sfw) noodles \uD83C\uDF5D follow my main page for daily lewds, nudes & tease videos ~ ... So ya wanna see my titties, huh? ⬇️ read this! ✨ New weekly content including: lewds, nudes, + tease gifs & tease vids ✨ \uD83C\uDF38 cute & sexy captions",
            rating = 4.5,
            power = 225,
            month = "April",
            day = "Wednesday",
            year = "1998",
            likes = 630709,
            photos = mapOf(),
            fans = listOf(),
            types = listOf("latin", "folk", "electronica"),
            ),

        )


    override suspend fun getAllStars(page: Int, limit: Int): Response {
        TODO("Not yet implemented")
    }

    override suspend fun searchStars(name: String): Response {
        TODO("Not yet implemented")
    }
}